### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by yijunyu** [trusted-programming/crusts#1]
# Tasks

## Functionality
- [x] Componentize TXL as a platform-independent Rust library, see https://github.com/trusted-programming/txl-rs
- [x] Add an option `-c2rust` to perform C2Rust only
- [x] Provide a number of precompiled transformations for Safe to Unsafe transformations
- [x] Provide a number of precompiled transformations for Idiomatic transformations, e.g., stdio, cint, etc.
- [ ] Integrate with user-defined TXL transformations
- [ ] Integrate with raw-pointer analysis tool developed by Bristol
